[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.backends.legacy:build"

[project]
name = "fairsharer"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "numpy"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff"
]